spring:
  application:
    name: nft-sync-service
 
  data:
    mongodb:
      uri: mongodb+srv://TradeScrap:TradeScrap@cluster0-8570y.mongodb.net/NFT_Matcher?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      repositories:
        enabled: true
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB